In [1]:
# Importación de Pandas
import pandas as pd # type: ignore
pd.options.display.float_format = '{:.2f}'.format
print("Pandas importado exitosamente.")

Pandas importado exitosamente.

In [2]:
#Conexión a carpeta de archivos
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# PERFILADO DEL PRIMER DATASET

In [3]:
# Importación del primer dataset
Data_Frame1 = pd.read_csv(r'/content/drive/MyDrive/UAIN1008R_Proyecto/datos/raw/Red vial nacional del Sistema Nacional de Carreteras 2022 a 2024 - Ministerio de Transportes y Comunicaciones – MTC.csv', encoding = 'latin1', sep=';')
print("Tamaño de la tabla: ", Data_Frame1.shape)

Data_Frame1.head()

Tamaño de la tabla:  (27290, 21)

,ID_RVN,ID_DEPARTAMENTO,DEPARTAMENTO,CODIGO_RUTA,TRAYECTORIA,INICIO,FINAL,CLASIFICACION_EJE,JERARQUIA,LONGITUD,...,SUPERFICIE,SUPERFICIE_L,ESTADO,ESTADO_L,CODIGO_CONCESION,NOMBRE_CONCESION,CODIGO_LOGISTICO,CORREDOR_LOGISTICO,FECHA_CORTE,ES_CONCES
0,1,20,PIURA,PE-02,Emp. PE-1N (Dv. Paita) - Paita,0.00,7.92,Transversal,RN,7.92,...,1,Pavimentado,1,Bueno,2,Eje Multimodal Amazonas Norte,C02,CO 2: Paita - Piura- Dv. Olmos,20221231,1
1,2,20,PIURA,PE-02,Emp. PE-1N (Dv. Paita) - Paita,7.92,40.09,Transversal,RN,32.18,...,1,Pavimentado,1,Bueno,2,Eje Multimodal Amazonas Norte,C02,CO 2: Paita - Piura- Dv. Olmos,20221231,1
2,3,20,PIURA,PE-02,Emp. PE-1N (Dv. Paita) - Paita,40.09,49.06,Transversal,RN,8.96,...,1,Pavimentado,1,Bueno,2,Eje Multimodal Amazonas Norte,C02,CO 2: Paita - Piura- Dv. Olmos,20221231,1
3,4,20,PIURA,PE-02A,Emp. PE-1N J (Dv. Huancabamba) - Buenos Aires ...,0.00,19.72,Transversal,RN,19.72,...,1,Pavimentado,1,Bueno,7,Emp.PE-1B-Buenos Aires - Canchaque,ALC02,Alimentador del corredor logístico 02,20221231,1
4,5,20,PIURA,PE-02A,Emp. PE-1N J (Dv. Huancabamba) - Buenos Aires ...,19.72,27.34,Transversal,RN,7.62,...,1,Pavimentado,1,Bueno,7,Emp.PE-1B-Buenos Aires - Canchaque,ALC02,Alimentador del corredor logístico 02,20221231,1

In [4]:
# Tipos de datos
Data_Frame1.dtypes

ID_RVN                  int64
ID_DEPARTAMENTO         int64
DEPARTAMENTO           object
CODIGO_RUTA            object
TRAYECTORIA            object
INICIO                float64
FINAL                 float64
CLASIFICACION_EJE      object
JERARQUIA              object
LONGITUD              float64
NRO_CARRILES            int64
SUPERFICIE              int64
SUPERFICIE_L           object
ESTADO                  int64
ESTADO_L               object
CODIGO_CONCESION        int64
NOMBRE_CONCESION       object
CODIGO_LOGISTICO       object
CORREDOR_LOGISTICO     object
FECHA_CORTE             int64
ES_CONCES               int64
dtype: object

In [5]:
# Total de nulos y % de nulos por columna
nulos = Data_Frame1.isnull().sum()
porcentaje_nulos = (Data_Frame1.isnull().mean() * 100).round(2)

tabla_nulos = pd.DataFrame({'Total Nulos': nulos, 'Porcentaje Nulos': porcentaje_nulos})

print("REPORTE DE VALORES NULOS: ")
tabla_nulos

REPORTE DE VALORES NULOS:

                    Total Nulos  Porcentaje Nulos
ID_RVN                        0              0.00
ID_DEPARTAMENTO               0              0.00
DEPARTAMENTO                  0              0.00
CODIGO_RUTA                   0              0.00
TRAYECTORIA                   0              0.00
INICIO                        0              0.00
FINAL                         0              0.00
CLASIFICACION_EJE             0              0.00
JERARQUIA                     0              0.00
LONGITUD                      0              0.00
NRO_CARRILES                  0              0.00
SUPERFICIE                    0              0.00
SUPERFICIE_L                  0              0.00
ESTADO                        0              0.00
ESTADO_L                      0              0.00
CODIGO_CONCESION              0              0.00
NOMBRE_CONCESION              0              0.00
CODIGO_LOGISTICO              0              0.00
CORREDOR_LOGISTICO            0              0.00
FECHA_CORTE                   0              0.00
ES_CONCES                     0              0.00

In [6]:
# Número de filas duplicadas
duplicados = Data_Frame1.duplicated().sum()

print("Número de filas duplicadas: ", duplicados)

Número de filas duplicadas:  0

In [7]:
# Rangos inconsistentes
tabla_rangos1 = pd.DataFrame({
    'CATEGORIA': ['ID_RVN','ID_DEPARTAMENTO','INICIO','FINAL','LONGITUD','NRO_CARRILES','SUPERFICIE','ESTADO','CODIGO_CONCESION','FECHA_CORTE','ES_CONCES'],
    'MINIMO': [Data_Frame1['ID_RVN'].min(), Data_Frame1['ID_DEPARTAMENTO'].min(), Data_Frame1['INICIO'].min(), Data_Frame1['FINAL'].min(), Data_Frame1['LONGITUD'].min(), Data_Frame1['NRO_CARRILES'].min(), Data_Frame1['SUPERFICIE'].min(), Data_Frame1['ESTADO'].min(), Data_Frame1['CODIGO_CONCESION'].min(), Data_Frame1['FECHA_CORTE'].min(), Data_Frame1['ES_CONCES'].min()],
    'MAXIMO': [Data_Frame1['ID_RVN'].max(), Data_Frame1['ID_DEPARTAMENTO'].max(), Data_Frame1['INICIO'].max(), Data_Frame1['FINAL'].max(), Data_Frame1['LONGITUD'].max(), Data_Frame1['NRO_CARRILES'].max(), Data_Frame1['SUPERFICIE'].max(), Data_Frame1['ESTADO'].max(), Data_Frame1['CODIGO_CONCESION'].max(), Data_Frame1['FECHA_CORTE'].max(), Data_Frame1['ES_CONCES'].max()]
})

tabla_rangos1

           CATEGORIA      MINIMO      MAXIMO
0             ID_RVN        1.00    27290.00
1    ID_DEPARTAMENTO        1.00       25.00
2             INICIO        0.00     1988.08
3              FINAL        0.05     1988.98
4           LONGITUD        0.00      269.17
5       NRO_CARRILES       -1.00        7.00
6         SUPERFICIE        1.00       11.00
7             ESTADO       -1.00        3.00
8   CODIGO_CONCESION        1.00      999.00
9        FECHA_CORTE 20221231.00 20241231.00
10         ES_CONCES        0.00        1.00

In [8]:
# Estadísticas descriptivas para columnas numéricas
Data_Frame1.describe()

,ID_RVN,ID_DEPARTAMENTO,INICIO,FINAL,LONGITUD,NRO_CARRILES,SUPERFICIE,ESTADO,CODIGO_CONCESION,FECHA_CORTE,ES_CONCES
count,27290.00,27290.00,27290.00,27290.00,27290.00,27290.00,27290.00,27290.00,27290.00,27290.00,27290.00
mean,13645.50,11.14,320.33,324.63,4.29,1.33,4.21,1.54,820.93,20233810.99,0.18
std,7878.09,6.77,427.38,427.36,8.27,1.24,4.49,0.65,379.91,8122.14,0.38
min,1.00,1.00,0.00,0.05,0.00,-1.00,1.00,-1.00,1.00,20221231.00,0.00
25%,6823.25,6.00,52.08,55.51,0.53,1.00,1.00,1.00,999.00,20231231.00,0.00
50%,13645.50,10.00,135.00,138.82,1.63,2.00,1.00,1.00,999.00,20240731.00,0.00
75%,20467.75,15.00,364.41,367.35,4.95,2.00,11.00,2.00,999.00,20241231.00,0.00
max,27290.00,25.00,1988.08,1988.98,269.17,7.00,11.00,3.00,999.00,20241231.00,1.00

In [9]:
# Detección de outliers utilizando el método del IQR
numericos1 = Data_Frame1.select_dtypes(include='number')

q1_1 = numericos1.quantile(0.25)
q3_1 = numericos1.quantile(0.75)
iqr_1 = q3_1 - q1_1
outliers_1 = ((numericos1 < (q1_1 - 1.5 * iqr_1)) | (numericos1 > (q3_1 + 1.5 * iqr_1))).sum()

print("Número de outliers por columna:")
outliers_1

Número de outliers por columna:

ID_RVN                 0
ID_DEPARTAMENTO        0
INICIO              3940
FINAL               3932
LONGITUD            2576
NRO_CARRILES        5223
SUPERFICIE             0
ESTADO               185
CODIGO_CONCESION    4916
FECHA_CORTE            0
ES_CONCES           4916
dtype: int64

In [10]:
# Función para ver los outliers por fila
mascara = (numericos1 < (q1_1 - 1.5 * iqr_1)) | (numericos1 > (q3_1 + 1.5 * iqr_1))
filas_outliers = Data_Frame1[mascara.any(axis=1)]
print(filas_outliers)

       ID_RVN  ID_DEPARTAMENTO DEPARTAMENTO CODIGO_RUTA  \
0           1               20        PIURA       PE-02
1           2               20        PIURA       PE-02
2           3               20        PIURA       PE-02
3           4               20        PIURA      PE-02A
4           5               20        PIURA      PE-02A
...       ...              ...          ...         ...
27272   27273               20        PIURA       PE-3N
27273   27274               20        PIURA       PE-3N
27283   27284               20        PIURA       PE-3N
27284   27285                6    CAJAMARCA      PE-3ND
27285   27286                6    CAJAMARCA      PE-3ND

                                             TRAYECTORIA  INICIO   FINAL  \
0                         Emp. PE-1N (Dv. Paita) - Paita    0.00    7.92
1                         Emp. PE-1N (Dv. Paita) - Paita    7.92   40.09
2                         Emp. PE-1N (Dv. Paita) - Paita   40.09   49.06
3      Emp. PE-1N J (Dv. Huancabamba) - Buenos Aires ...    0.00   19.72
4      Emp. PE-1N J (Dv. Huancabamba) - Buenos Aires ...   19.72   27.34
...                                                  ...     ...     ...
27272  Repartición La Oroya (PE-22) - Huánuco (PE-18 ... 1853.54 1861.63
27273  Repartición La Oroya (PE-22) - Huánuco (PE-18 ... 1737.67 1739.76
27283  Repartición La Oroya (PE-22) - Huánuco (PE-18 ... 1734.83 1735.54
27284  Emp. PE-3N (Cutervo) - Socota  San Andrés de ...   43.21   44.00
27285  Emp. PE-3N (Cutervo) - Socota  San Andrés de ...   48.27   48.28

               CLASIFICACION_EJE JERARQUIA  LONGITUD  ...  SUPERFICIE  \
0                    Transversal        RN      7.92  ...           1
1                    Transversal        RN     32.18  ...           1
2                    Transversal        RN      8.96  ...           1
3                    Transversal        RN     19.72  ...           1
4                    Transversal        RN      7.62  ...           1
...                          ...       ...       ...  ...         ...
27272  Longitudinal de la Sierra        RN      8.09  ...          11
27273  Longitudinal de la Sierra        RN      2.09  ...          11
27283  Longitudinal de la Sierra        RN      0.71  ...          11
27284                      Ramal        RN      0.79  ...           3
27285                      Ramal        RN      0.01  ...           3

              SUPERFICIE_L ESTADO  ESTADO_L CODIGO_CONCESION  \
0              Pavimentado      1     Bueno                2
1              Pavimentado      1     Bueno                2
2              Pavimentado      1     Bueno                2
3              Pavimentado      1     Bueno                7
4              Pavimentado      1     Bueno                7
...                    ...    ...       ...              ...
27272  Asfaltado económico      1     Bueno              999
27273  Asfaltado económico      1     Bueno              999
27283  Asfaltado económico      1     Bueno              999
27284          Sin afirmar      2   Regular              999
27285          Sin afirmar      2   Regular              999

                         NOMBRE_CONCESION CODIGO_LOGISTICO  \
0           Eje Multimodal Amazonas Norte              C02
1           Eje Multimodal Amazonas Norte              C02
2           Eje Multimodal Amazonas Norte              C02
3      Emp.PE-1B-Buenos Aires - Canchaque            ALC02
4      Emp.PE-1B-Buenos Aires - Canchaque            ALC02
...                                   ...              ...
27272                     No concesionado               NC
27273                     No concesionado               NC
27283                     No concesionado               NC
27284                     No concesionado               NC
27285                     No concesionado               NC

                          CORREDOR_LOGISTICO FECHA_CORTE  ES_CONCES
0             CO 2: Paita - Piura- Dv. Olmos    20221231          1
1             CO 2: Paita - Piura- Dv. Olmos    20221231          1
2             CO 2: Paita - Piura- Dv. Olmos    20221231          1
3      Alimentador del corredor logístico 02    20221231          1
4      Alimentador del corredor logístico 02    20221231          1
...                                      ...         ...        ...
27272                         No corresponde    20241231          0
27273                         No corresponde    20241231          0
27283                         No corresponde    20241231          0
27284                         No corresponde    20241231          0
27285                         No corresponde    20241231          0

[12884 rows x 21 columns]

# Análisis de outliers:
Se aplicó el método del Rango Intercuartílico (IQR) para detectar valores atípicos en las columnas numéricas. Si bien se identificaron valores fuera del rango intercuartílico en columnas como LONGITUD, INICIO y FINAL, tras una revisión manual se determinó que estos corresponden a variaciones propias de la red vial nacional, donde coexisten tramos cortos de pocos metros junto a tramos de cientos de kilómetros según la región y jerarquía de la vía. Ningún valor resultó inválido, por lo que se decidió conservar todos los registros sin eliminación ni imputación.

In [11]:
for col in Data_Frame1.select_dtypes(include='object').columns:
    print(f"\n{'='*40}")
    print(f"COLUMNA: {col}")
    print(f"Valores únicos: {Data_Frame1[col].nunique()}")
    vc = Data_Frame1[col].value_counts()
    raras = vc[vc < (len(Data_Frame1) * 0.01)]  # menos del 1%
    print(f"Categorías raras (< 1%): {len(raras)}")
    if len(raras) > 0:
        print(raras)
    else:
        print("Sin categorías raras ✅")

========================================
COLUMNA: DEPARTAMENTO
Valores únicos: 25
Categorías raras (< 1%): 4
DEPARTAMENTO
CALLAO           203
MADRE DE DIOS    190
TUMBES           141
LORETO            73
Name: count, dtype: int64

========================================
COLUMNA: CODIGO_RUTA
Valores únicos: 161
Categorías raras (< 1%): 138
CODIGO_RUTA
PE-28A    252
PE-28C    252
PE-32A    236
PE-30B    232
PE-5NC    221
         ...
PE-1SH      4
PE-1SB      4
PE-1NQ      4
PE-22C      4
PE-3NE      4
Name: count, Length: 138, dtype: int64

========================================
COLUMNA: TRAYECTORIA
Valores únicos: 167
Categorías raras (< 1%): 144
TRAYECTORIA
Emp.PE-1S E (Dv. Huaytará) - Independencia - Humay - Huáncano - Pámpano (PE 28 D) - Pte. Huaytara - Pte. Cuyahuasi - Pte. Tullpa - Pte. Dos de Mayo - Pte. Muchic - Pte. Ana Teresa - Pte. Tsej Tsi - Pte. Tranca - Huaytará - Pte. Suyacuna - Pte. Mollep    252
Emp. PE-28 B (San Francisco)  Quimbiri  Pichari  Pedro Ruiz  Trincavini - Quisto Central - Natividad  Puerto Ene  Puerto Anapati  Mencoriari - Cubantía - San Martín de Pangoa - Emp. PE-5S (Mazamari)                                                 252
Emp. PE-30 A (Dv. Andamarca) - Andamarca - Querobamba - Huancapi - Cangallo -Emp. PE-3S (Abra Tocto)                                                                                                                                                          236
Emp. PE-30 A (Dv. Andahuaylas) - Dv. San Pedro de Lircay - Pampachiri - Abra Campanayoc - Abra Ayalaylla - Catala - Huarocopata - Emp. PE-3S (Andahuaylas)                                                                                                    232
Emp. PE-34 A (Dv. Vizcachane) - Vizcachane - Pulpera - Negro Mayo - Dv. Tintaya (PE-3S K) - Quello - Emp. PE-3S G (Yauri)                                                                                                                                     221
                                                                                                                                                                                                                                                             ...
Emp. PE-1N (Dv. Chimbote) - Dv. Lacramarca - Emp. PE-1N (Santa).                                                                                                                                                                                                4
Emp. PE-3N (Dv. Aquia) - Mojón - Emp. PE-3N                                                                                                                                                                                                                     4
Emp. PE-22 - Cieneguilla - San Mateo - Emp. PE-22                                                                                                                                                                                                               2
Emp. PE-08 B (Pte. Utcubamba) - Emp. AM-103 (PE-5N G)                                                                                                                                                                                                           2
Emp. PE-20 (Ovalo 200 Millas)  Aeropuerto (Ovalo Faucett)  Av Faucett - Pte. Faucett  Av. Morales Duarez  Emp. PE 20 (Av. Nestor Gambetta). Incluye el acceso al Límite Provincial Lima - Callao Emp. Av. Paseo Japón) y accesos (Puentes) al Ae            2
Name: count, Length: 144, dtype: int64

========================================
COLUMNA: CLASIFICACION_EJE
Valores únicos: 6
Categorías raras (< 1%): 0
Sin categorías raras ✅

========================================
COLUMNA: JERARQUIA
Valores únicos: 1
Categorías raras (< 1%): 0
Sin categorías raras ✅

========================================
COLUMNA: SUPERFICIE_L
Valores únicos: 9
Categorías raras (< 1%): 2
SUPERFICIE_L
Proyectado    136
Proyectada     49
Name: count, dtype: int64

========================================
COLUMNA: ESTADO_L
Valores únicos: 4
Categorías raras (< 1%): 1
ESTADO_L
Información no disponible    185
Name: count, dtype: int64

========================================
COLUMNA: NOMBRE_CONCESION
Valores únicos: 17
Categorías raras (< 1%): 9
NOMBRE_CONCESION
Concesionaria Peruana de Vías                                                                       272
Red Vial N° 4 - Tramo Vial: Pativilca - Santa - Trujillo y Puerto Salaverry                         228
IIRSA Centro - Tramo 2: Pte. Ricardo Palma - La Oroya - Huancayo y La Oroya - Dv. Cerro de Pasco    208
IIRSA Sur - Tramo 3: Inambari - Iñapari                                                             162
Red Vial N° 6 - Tramo Vial: Puente Pucusana - Cerro Azul  Ica                                      140
Red Vial N° 5 - Tramo Vial: Ancón - Huacho - Pativilca                                              120
Ovalo Chancay Huaral Acos                                                                            68
Emp.PE-1B-Buenos Aires - Canchaque                                                                   38
Nvo. Mocupe - Cayaltí - Oyotún                                                                       32
Name: count, dtype: int64

========================================
COLUMNA: CODIGO_LOGISTICO
Valores únicos: 81
Categorías raras (< 1%): 55
CODIGO_LOGISTICO
C01        260
ALEE02     258
C08        256
C10        248
ALC06      239
03CRL26    234
02CRL18    228
03CRL35    222
02CRL20    208
03CRL24    202
02CRL13    202
C12        198
02CRL04    179
03CRL28    176
C15        175
02CRL17    168
02CRL19    165
03CRL33    164
03CRL37    156
C09        154
02CRL06    154
C20        148
02CRL11    146
03CRL27    146
02CRL12    144
C04        138
02CRL16    136
04CRL39    134
C18        134
C17        130
04CRL40    127
C11        125
C13        122
04CRL41    120
03CRL29    116
03CRL36    114
C19        114
02CRL14    114
03CRL32    106
ALC02       99
C07         97
03CRL30     92
ALEE01      90
02CRL05     90
C06         88
ALC11       88
ALC07       82
03CRL25     78
03CRL22     76
ALC16       76
C02         69
ALC15       69
01CRL03     66
03CRL31     66
C14         64
Name: count, dtype: int64

========================================
COLUMNA: CORREDOR_LOGISTICO
Valores únicos: 81
Categorías raras (< 1%): 55
CORREDOR_LOGISTICO
CO 1: Chiclayo - Moyobamba - Tarapoto - Yurimaguas - Iquitos                260
Alimentador del eje estructurante 02                                        258
CO 8: Cusco - Puerto Maldonado- Iñapari (Frontera con Brasil)               256
CO 10: Abancay - Ayacucho- Huancayo- La Oroya                               248
Alimentador del corredor logístico 06                                       239
Corredor Trujillo - Huamachuco - Cajamarca                                  234
Corredor Cusco - Puerto Maldonado - Iñapari                                 228
Corredor La Mreced - Villa Rica - Von Humboldt                              222
Corredor Marginal de la Selva                                               208
Corredor La Unión - Huánuco                                                 202
Corredor Minero                                                             202
CO 12: Tarapoto - Aucayacu- Tocache - Tingo María                           198
Corredor Piura - Tumbes - Frontera con Ecuador                              179
Corredor Cañete - Lunahuaná - Huancayo                                      176
CO 15: Piura - Tumbes- Puente Internacional (Frontera con Ecuador)          175
Corredor Cusco - Desaguadero                                                168
Corredor Tarma - La Merced - Satipo - Mazamari                              165
Corredor Juliaca - Puerto Maldonado                                         164
Corredor Cutervo - Chota - Cajamarca                                        156
CO 9: Ayacucho- Pisco                                                       154
Corredor Callejón de Huaylas                                                154
CO 20: Dv. Quilca - Matarani - Ilo - Tacna                                  148
Corredor Los Libertadores                                                   146
Corredor Chiclayo - Cutervo - Jaén                                          146
Corredor Nazca - Cusco                                                      144
CO4: Corredor Logístico 4: Marcona - Nazca - Abancay - Cusco                138
Corredor La Oroya - Ayacucho                                                136
Corredor Santa - Huacrachuco - Uchiza                                       134
CO 18: Chimbote- Huacrachuco- Tocache                                       134
CO 17: La Oroya - Tarma- La Merced- Satipo                                  130
Corredor Bagua - Santa Maria de Nieva - Saramiriza                          127
CO 11: Cusco - Juliaca- Puno- Desaguadero (Frontera con Bolivia)            125
CO 13: Pativilca - Conococha - Huaraz- Carhuaz                              122
Corredor Satipo - Pachiza - Quimbiri                                        120
Corredor Chincha - Huancavelica - Izcuchaca                                 116
Corredor Jaén - San Ignacio - Namballe                                      114
CO 19: Corredor Logístico 19: Salaverry - Trujillo - Shorey - Huamachuco    114
Corredor Matarani - Arequipa - Juliaca                                      114
Corredor Ayacucho - Abancay                                                 106
Alimentador del corredor logístico 02                                        99
CO 7: Matarani - Ilo- Moquegua- Desaguadero (Frontera con Bolivia)           97
Corredor Ilo - Moquegua - Desaguadero                                        92
Alimentador del eje estructurante 01                                         90
Corredor Arequipa - Tacna - Frontera con Chile                               90
CO 6: Arequipa - Moquegua- Tacna- La Concordia (Frontera con Chile)          88
Alimentador del corredor logístico 11                                        88
Alimentador del corredor logístico 07                                        82
Corredor Casma - Huaraz                                                      78
Corredor Chancay - Huaral - Acos - Unish                                     76
Alimentador del corredor logístico 16                                        76
CO 2: Paita - Piura- Dv. Olmos                                               69
Alimentador del corredor logístico 15                                        69
Corredor Central                                                             66
Corredor Moquegua - Puno                                                     66
CO 14: Corredor Logístico 14: Ciudad de Dios - Cajamarca - Chachapoyas       64
Name: count, dtype: int64

In [12]:
# Tabla de métricas del primer Dataset

# -- Completitud: Porcentaje de valores no nulos
completitud1 = round((1 - Data_Frame1.isnull().sum().sum() / Data_Frame1.size) * 100, 2)

# -- Unicidad: Porcentaje de filas únicas
unicidad1 = round((1 - Data_Frame1.duplicated().sum() / len(Data_Frame1)) * 100, 2)

# -- Consistencia: Porcentaje de columnas sin problemas de rango o formato
cols_totales1 = 21
cols_con_problema1 = 3
consistencia1 = round(((cols_totales1 - cols_con_problema1) / cols_totales1) * 100, 2)

# Creación de la tabla de métricas
tabla_metricas1 = pd.DataFrame({
    'Dataset': ["Red vial nacional del Sistema Nacional de Carreteras 2022 a 2024"],
    'Filas': [len(Data_Frame1)],
    'Completitud': [completitud1],
    'Unicidad': [unicidad1],
    'Consistencia': [consistencia1]
})

print("Métricas de calidad del dataset:")
tabla_metricas1

Métricas de calidad del dataset:

,Dataset,Filas,Completitud,Unicidad,Consistencia
0,Red vial nacional del Sistema Nacional de Carr...,27290,100.00,100.00,85.71

# PERFILADO DEL SEGUNDO DATASET

In [13]:
# Importación del segundo dataset
Data_Frame2 = pd.read_csv(r'/content/drive/MyDrive/UAIN1008R_Proyecto/datos/raw/Dataset GEI CSV_0.csv', sep=';')
print("Tamaño de la tabla: ", Data_Frame2.shape)

Data_Frame2.head()

Tamaño de la tabla:  (358, 14)

,FECHA_CORTE,ANIO,SECTOR,CATEGORIA,SUBCATEGORIA,FUENTE_DE_EMISION,IPCC_CLASF,DIOXIDO_DE_CARBONO_GGCO2,METANO_GGCH4,METANO_EQUIVALENTE_GGCO2EQ,OXIDO_NITROSO_GGN2O,OXIDO_NITROSO_EQUIVALENTE_GGCO2EQ,HFC_GGCO2EQ,EMISIONES_GEI_GGCO2EQ
0,20240521.00,2019.00,ENERGIA,ACTIVIDADES DE QUEMA DE COMBUSTIBLES,INDUSTRIAS DE ENERGIA,PRODUCCION DE ELECTRICIDAD Y CALOR COMO ACTIVI...,1A1a,8769.28,0.49,13.63,0.06,16.25,NaN,8799.16
1,20240521.00,2019.00,ENERGIA,ACTIVIDADES DE QUEMA DE COMBUSTIBLES,INDUSTRIAS DE ENERGIA,REFINACION DE PETROLEO,1A1b,1973.19,0.04,0.98,0.00,0.93,NaN,1975.11
2,20240521.00,2019.00,ENERGIA,ACTIVIDADES DE QUEMA DE COMBUSTIBLES,INDUSTRIAS DE ENERGIA,FABRICACION DE COMBUSTIBLES SOLIDOS Y OTRAS IN...,1A1c,1951.02,0.04,1.18,0.01,1.49,NaN,1953.69
3,20240521.00,2019.00,ENERGIA,ACTIVIDADES DE QUEMA DE COMBUSTIBLES,INDUSTRIAS MANUFACTURERAS Y DE LA CONSTRUCCION,MINERIA (CON EXCEPCION DE COMBUSTIBLES) Y CANT...,1A2i,1489.46,0.06,1.62,0.01,2.94,NaN,1494.02
4,20240521.00,2019.00,ENERGIA,ACTIVIDADES DE QUEMA DE COMBUSTIBLES,INDUSTRIAS MANUFACTURERAS Y DE LA CONSTRUCCION,INDUSTRIA NO ESPECIFICADA,1A2m,7666.42,1.56,43.67,0.19,49.54,NaN,7759.62

In [14]:
# Tipos de datos
Data_Frame2.dtypes

FECHA_CORTE                          float64
ANIO                                 float64
SECTOR                                object
CATEGORIA                             object
SUBCATEGORIA                          object
FUENTE_DE_EMISION                     object
IPCC_CLASF                            object
DIOXIDO_DE_CARBONO_GGCO2             float64
METANO_GGCH4                         float64
METANO_EQUIVALENTE_GGCO2EQ           float64
OXIDO_NITROSO_GGN2O                  float64
OXIDO_NITROSO_EQUIVALENTE_GGCO2EQ    float64
HFC_GGCO2EQ                          float64
EMISIONES_GEI_GGCO2EQ                float64
dtype: object

In [15]:
# Total de nulos y % de nulos por columna
nulos2 = Data_Frame2.isnull().sum()
porcentaje_nulos2 = (Data_Frame2.isnull().mean() * 100).round(2)

tabla_nulos2 = pd.DataFrame({'Total Nulos': nulos2, 'Porcentaje Nulos': porcentaje_nulos2})

print("REPORTE DE VALORES NULOS: ")
tabla_nulos2

REPORTE DE VALORES NULOS:

                                   Total Nulos  Porcentaje Nulos
FECHA_CORTE                                  1              0.28
ANIO                                         1              0.28
SECTOR                                       1              0.28
CATEGORIA                                    1              0.28
SUBCATEGORIA                                29              8.10
FUENTE_DE_EMISION                           57             15.92
IPCC_CLASF                                   1              0.28
DIOXIDO_DE_CARBONO_GGCO2                   132             36.87
METANO_GGCH4                               162             45.25
METANO_EQUIVALENTE_GGCO2EQ                 162             45.25
OXIDO_NITROSO_GGN2O                        176             49.16
OXIDO_NITROSO_EQUIVALENTE_GGCO2EQ          176             49.16
HFC_GGCO2EQ                                351             98.04
EMISIONES_GEI_GGCO2EQ                       35              9.78

In [16]:
# Número de filas duplicadas
duplicados2 = Data_Frame2.duplicated().sum()

print("Número de filas duplicadas: ", duplicados2)

Número de filas duplicadas:  0

In [17]:
# Rangos inconsistentes
tabla_rangos2 = pd.DataFrame({
    'CATEGORIA': ['FECHA_CORTE','ANIO','DIOXIDO_DE_CARBONO_GGCO2','METANO_GGCH4','METANO_EQUIVALENTE_GGCO2EQ','OXIDO_NITROSO_GGN2O','OXIDO_NITROSO_EQUIVALENTE_GGCO2EQ','HFC_GGCO2EQ','EMISIONES_GEI_GGCO2EQ'],
    'MINIMO': [Data_Frame2['FECHA_CORTE'].min(), Data_Frame2['ANIO'].min(), Data_Frame2['DIOXIDO_DE_CARBONO_GGCO2'].min(), Data_Frame2['METANO_GGCH4'].min(), Data_Frame2['METANO_EQUIVALENTE_GGCO2EQ'].min(), Data_Frame2['OXIDO_NITROSO_GGN2O'].min(), Data_Frame2['OXIDO_NITROSO_EQUIVALENTE_GGCO2EQ'].min(), Data_Frame2['HFC_GGCO2EQ'].min(), Data_Frame2['EMISIONES_GEI_GGCO2EQ'].min()],
    'MAXIMO': [Data_Frame2['FECHA_CORTE'].max(), Data_Frame2['ANIO'].max(), Data_Frame2['DIOXIDO_DE_CARBONO_GGCO2'].max(), Data_Frame2['METANO_GGCH4'].max(), Data_Frame2['METANO_EQUIVALENTE_GGCO2EQ'].max(), Data_Frame2['OXIDO_NITROSO_GGN2O'].max(), Data_Frame2['OXIDO_NITROSO_EQUIVALENTE_GGCO2EQ'].max(), Data_Frame2['HFC_GGCO2EQ'].max(), Data_Frame2['EMISIONES_GEI_GGCO2EQ'].max()]
})

tabla_rangos2

                           CATEGORIA      MINIMO      MAXIMO
0                        FECHA_CORTE 20240521.00 20240521.00
1                               ANIO     2000.00     2019.00
2           DIOXIDO_DE_CARBONO_GGCO2    -2455.67    64643.22
3                       METANO_GGCH4        0.00      558.06
4         METANO_EQUIVALENTE_GGCO2EQ        0.00    15625.81
5                OXIDO_NITROSO_GGN2O        0.00       25.86
6  OXIDO_NITROSO_EQUIVALENTE_GGCO2EQ        0.03     6853.68
7                        HFC_GGCO2EQ       18.94      909.91
8              EMISIONES_GEI_GGCO2EQ    -2455.67    64643.22

In [18]:
# Estadísticas descriptivas para columnas numéricas
Data_Frame2.describe()

,FECHA_CORTE,ANIO,DIOXIDO_DE_CARBONO_GGCO2,METANO_GGCH4,METANO_EQUIVALENTE_GGCO2EQ,OXIDO_NITROSO_GGN2O,OXIDO_NITROSO_EQUIVALENTE_GGCO2EQ,HFC_GGCO2EQ,EMISIONES_GEI_GGCO2EQ
count,357.00,357.00,226.00,196.00,196.00,182.00,182.00,7.00,323.00
mean,20240521.00,2010.86,3511.30,45.94,1286.18,1.48,391.79,305.46,3464.67
std,0.00,6.07,9559.52,111.85,3131.89,4.81,1273.46,313.31,8304.97
min,20240521.00,2000.00,-2455.67,0.00,0.00,0.00,0.03,18.94,-2455.67
25%,20240521.00,2005.00,73.94,0.04,1.11,0.00,1.02,94.08,90.31
50%,20240521.00,2012.00,324.06,1.43,40.14,0.02,4.65,204.85,642.50
75%,20240521.00,2016.00,1967.65,30.27,847.82,0.50,131.61,408.17,2940.00
max,20240521.00,2019.00,64643.22,558.06,15625.81,25.86,6853.68,909.91,64643.22

In [19]:
# Detección de outliers utilizando el método del IQR
numericos2 = Data_Frame2.select_dtypes(include='number')

q1_2 = numericos2.quantile(0.25)
q3_2 = numericos2.quantile(0.75)
iqr_2 = q3_2 - q1_2
outliers_2 = ((numericos2 < (q1_2 - 1.5 * iqr_2)) | (numericos2 > (q3_2 + 1.5 * iqr_2))).sum()

print("Número de outliers por columna:")
outliers_2

Número de outliers por columna:

FECHA_CORTE                           0
ANIO                                  0
DIOXIDO_DE_CARBONO_GGCO2             35
METANO_GGCH4                         31
METANO_EQUIVALENTE_GGCO2EQ           31
OXIDO_NITROSO_GGN2O                  26
OXIDO_NITROSO_EQUIVALENTE_GGCO2EQ    26
HFC_GGCO2EQ                           1
EMISIONES_GEI_GGCO2EQ                42
dtype: int64

In [20]:
# Función para ver los outliers por fila
mascara = (numericos2 < (q1_2 - 1.5 * iqr_2)) | (numericos2 > (q3_2 + 1.5 * iqr_2))
filas_outliers = Data_Frame2[mascara.any(axis=1)]
print(filas_outliers)

     FECHA_CORTE    ANIO                                             SECTOR  \
0    20240521.00 2019.00                                           ENERGIA
4    20240521.00 2019.00                                           ENERGIA
6    20240521.00 2019.00                                           ENERGIA
18   20240521.00 2019.00                                           ENERGIA
29   20240521.00 2019.00          PROCESOS INDUSTRIALES Y USO DE PRODUCTOS
..           ...     ...                                                ...
336  20240521.00 2000.00  AGRICULTURA, SILVICULTURA Y OTROS USOS DE LA T...
346  20240521.00 2000.00  AGRICULTURA, SILVICULTURA Y OTROS USOS DE LA T...
348  20240521.00 2000.00  AGRICULTURA, SILVICULTURA Y OTROS USOS DE LA T...
349  20240521.00 2000.00  AGRICULTURA, SILVICULTURA Y OTROS USOS DE LA T...
352  20240521.00 2000.00                                           DESECHOS

                                             CATEGORIA  \
0                ACTIVIDADES DE QUEMA DE COMBUSTIBLES
4                ACTIVIDADES DE QUEMA DE COMBUSTIBLES
6                ACTIVIDADES DE QUEMA DE COMBUSTIBLES
18   EMISIONES FUGITIVAS PROVENIENTES DE LA FABRICA...
29   USO DE PRODUCTOS SUSTITUTOS DE LAS SUSTANCIAS ...
..                                                 ...
336                                             GANADO
346  FUENTES AGREGADAS Y FUENTES DE EMISION NO-CO2 ...
348  FUENTES AGREGADAS Y FUENTES DE EMISION NO-CO2 ...
349  FUENTES AGREGADAS Y FUENTES DE EMISION NO-CO2 ...
352                    ELIMINACION DE DESECHOS SOLIDOS

                                          SUBCATEGORIA  \
0                                INDUSTRIAS DE ENERGIA
4       INDUSTRIAS MANUFACTURERAS Y DE LA CONSTRUCCION
6                                           TRANSPORTE
18                              PETROLEO Y GAS NATURAL
29                  REFRIGERACION Y AIRE ACONDICIONADO
..                                                 ...
336                                                NaN
346                    EMISIONES POR QUEMA DE BIOMASA
348    EMISIONES DIRECTAS DE N2O DE SUELOS GESTIONADOS
349  EMISIONES INDIRECTAS DE N2O DE SUELOS GESTIONADOS
352                                                NaN

                                     FUENTE_DE_EMISION IPCC_CLASF  \
0    PRODUCCION DE ELECTRICIDAD Y CALOR COMO ACTIVI...       1A1a
4                            INDUSTRIA NO ESPECIFICADA       1A2m
6                                 TRANSPORTE TERRESTRE       1A3b
18                                         GAS NATURAL       1B2b
29                                                 NaN        2F1
..                                                 ...        ...
336                              FERMENTACION ENTERICA        3A1
346                    EMISIONES POR QUEMA DE BIOMASA         3C1
348    EMISIONES DIRECTAS DE N2O DE SUELOS GESTIONADOS        3C4
349  EMISIONES INDIRECTAS DE N2O DE SUELOS GESTIONADOS        3C5
352                    ELIMINACION DE DESECHOS SOLIDOS         4A

     DIOXIDO_DE_CARBONO_GGCO2  METANO_GGCH4  METANO_EQUIVALENTE_GGCO2EQ  \
0                     8769.28          0.49                       13.63
4                     7666.42          1.56                       43.67
6                    23385.01          9.03                      252.81
18                     265.37        273.83                     7667.31
29                        NaN           NaN                         NaN
..                        ...           ...                         ...
336                       NaN        509.99                    14279.75
346                       NaN         15.60                      436.70
348                       NaN           NaN                         NaN
349                       NaN           NaN                         NaN
352                       NaN        164.54                     4607.18

     OXIDO_NITROSO_GGN2O  OXIDO_NITROSO_EQUIVALENTE_GGCO2EQ  HFC_GGCO2EQ  \
0                   0.06                              16.25          NaN
4                   0.19                              49.54          NaN
6                   1.21                             321.13          NaN
18                  0.00                               0.81          NaN
29                   NaN                                NaN       909.91
..                   ...                                ...          ...
336                  NaN                                NaN          NaN
346                 1.30                             343.87          NaN
348                21.17                            5610.54          NaN
349                 7.70                            2039.89          NaN
352                  NaN                                NaN          NaN

     EMISIONES_GEI_GGCO2EQ
0                  8799.16
4                  7759.62
6                 23958.96
18                 7933.49
29                  909.91
..                     ...
336               14279.75
346                 780.57
348                5610.54
349                2039.89
352                4607.18

[88 rows x 14 columns]

# Análisis de outliers:
Se aplicó el método del Rango Intercuartílico (IQR) para detectar valores atípicos en las columnas numéricas. No se identificó ningún valor fuera del rango intercuartílico, lo que indica que los datos presentan una distribución uniforme y consistente a lo largo de todo el periodo registrado.

In [21]:
# Categorías raras
for col in Data_Frame2.select_dtypes(include='object').columns:
    print(f"\n{'='*40}")
    print(f"COLUMNA: {col}")
    print(f"Valores únicos: {Data_Frame2[col].nunique()}")
    vc = Data_Frame2[col].value_counts()
    raras = vc[vc < (len(Data_Frame2) * 0.01)]  # menos del 1%
    print(f"Categorías raras (< 1%): {len(raras)}")
    if len(raras) > 0:
        print(raras)
    else:
        print("Sin categorías raras ✅")

========================================
COLUMNA: SECTOR
Valores únicos: 4
Categorías raras (< 1%): 0
Sin categorías raras ✅

========================================
COLUMNA: CATEGORIA
Valores únicos: 13
Categorías raras (< 1%): 0
Sin categorías raras ✅

========================================
COLUMNA: SUBCATEGORIA
Valores únicos: 31
Categorías raras (< 1%): 0
Sin categorías raras ✅

========================================
COLUMNA: FUENTE_DE_EMISION
Valores únicos: 43
Categorías raras (< 1%): 0
Sin categorías raras ✅

========================================
COLUMNA: IPCC_CLASF
Valores únicos: 50
Categorías raras (< 1%): 0
Sin categorías raras ✅

In [22]:
# Tabla de métricas del segundo Dataset

# -- Completitud: Porcentaje de valores no nulos
completitud2 = round((1 - Data_Frame2.isnull().sum().sum() / Data_Frame2.size) * 100, 2)

# -- Unicidad: Porcentaje de filas únicas
unicidad2 = round((1 - Data_Frame2.duplicated().sum() / len(Data_Frame2)) * 100, 2)

# -- Consistencia: Porcentaje de columnas sin problemas de rango o formato
cols_totales2 = 14
cols_con_problema2 = 2
consistencia2 = round(((cols_totales2 - cols_con_problema2) / cols_totales2) * 100, 2)

# Creación de la tabla de métricas
tabla_metricas2 = pd.DataFrame({
    'Dataset': ["Dataset GEI CSV_0"],
    'Filas': [len(Data_Frame2)],
    'Completitud': [completitud2],
    'Unicidad': [unicidad2],
    'Consistencia': [consistencia2]
})

print("Métricas de calidad del dataset:")
tabla_metricas2

Métricas de calidad del dataset:

             Dataset  Filas  Completitud  Unicidad  Consistencia
0  Dataset GEI CSV_0    358        74.36    100.00         85.71

# PERFILADO DEL TERCER DATASET

In [23]:
# Importación del primer dataset
Data_Frame3 = pd.read_csv(r'/content/drive/MyDrive/UAIN1008R_Proyecto/datos/raw/Información Trafico - Carga y Operaciones - LAP Ene 2019 - Dic 2025 - Organismo Supervisor de la Inversión en Infraestructura de Transporte de Uso Público – OSITRAN.csv')
print("Tamaño de la tabla: ", Data_Frame3.shape)

Data_Frame3.head()

Tamaño de la tabla:  (84, 8)

,ANIO,MES,ENTIDAD PRESTADORA,CONCESION,TOTAL CARGA NACIONAL,TOTAL CARGA INTERNACIONA,TOTAL OPERACION NACIONAL,TOTAL OPERACION INTERNACIONAL
0,2019,1,LIMA AIRPORT PARTNERS S.R.L. - LAP,AEROPUERTO INTERNACIONAL JORGE CHÁVEZ,1892.71,21963.97,8437,7289
1,2019,2,LIMA AIRPORT PARTNERS S.R.L. - LAP,AEROPUERTO INTERNACIONAL JORGE CHÁVEZ,1887.86,15837.73,8096,6527
2,2019,3,LIMA AIRPORT PARTNERS S.R.L. - LAP,AEROPUERTO INTERNACIONAL JORGE CHÁVEZ,2257.34,18690.35,9056,7105
3,2019,4,LIMA AIRPORT PARTNERS S.R.L. - LAP,AEROPUERTO INTERNACIONAL JORGE CHÁVEZ,2108.85,17872.45,9338,6720
4,2019,5,LIMA AIRPORT PARTNERS S.R.L. - LAP,AEROPUERTO INTERNACIONAL JORGE CHÁVEZ,2153.86,18309.42,10353,6936

In [24]:
# Tipos de datos
Data_Frame3.dtypes

ANIO                               int64
MES                                int64
ENTIDAD PRESTADORA                object
CONCESION                         object
TOTAL CARGA NACIONAL             float64
TOTAL CARGA INTERNACIONA         float64
TOTAL OPERACION NACIONAL           int64
TOTAL OPERACION INTERNACIONAL      int64
dtype: object

In [25]:
# Total de nulos y % de nulos por columna
nulos3 = Data_Frame3.isnull().sum()
porcentaje_nulos3 = (Data_Frame3.isnull().mean() * 100).round(2)

tabla_nulos3 = pd.DataFrame({'Total Nulos': nulos3, 'Porcentaje Nulos': porcentaje_nulos3})

print("REPORTE DE VALORES NULOS: ")
tabla_nulos3

REPORTE DE VALORES NULOS:

                               Total Nulos  Porcentaje Nulos
ANIO                                     0              0.00
MES                                      0              0.00
ENTIDAD PRESTADORA                       0              0.00
CONCESION                                0              0.00
TOTAL CARGA NACIONAL                     0              0.00
TOTAL CARGA INTERNACIONA                 0              0.00
TOTAL OPERACION NACIONAL                 0              0.00
TOTAL OPERACION INTERNACIONAL            0              0.00

In [26]:
# Número de filas duplicadas
duplicados3 = Data_Frame3.duplicated().sum()

print("Número de filas duplicadas: ", duplicados3)

Número de filas duplicadas:  0

In [27]:
# Rangos inconsistentes
tabla_rangos3 = pd.DataFrame({
    'CATEGORIA': ['ANIO','MES','TOTAL CARGA NACIONAL','TOTAL CARGA INTERNACIONA','TOTAL OPERACION NACIONAL','TOTAL OPERACION INTERNACIONAL'],
    'MINIMO': [Data_Frame3['ANIO'].min(), Data_Frame3['MES'].min(), Data_Frame3['TOTAL CARGA NACIONAL'].min(), Data_Frame3['TOTAL CARGA INTERNACIONA'].min(), Data_Frame3['TOTAL OPERACION NACIONAL'].min(), Data_Frame3['TOTAL OPERACION INTERNACIONAL'].min()],
    'MAXIMO': [Data_Frame3['ANIO'].max(), Data_Frame3['MES'].max(), Data_Frame3['TOTAL CARGA NACIONAL'].max(), Data_Frame3['TOTAL CARGA INTERNACIONA'].max(), Data_Frame3['TOTAL OPERACION NACIONAL'].max(), Data_Frame3['TOTAL OPERACION INTERNACIONAL'].max()]
})

tabla_rangos3

                       CATEGORIA  MINIMO   MAXIMO
0                           ANIO 2019.00  2025.00
1                            MES    1.00    12.00
2           TOTAL CARGA NACIONAL  518.90  3141.59
3       TOTAL CARGA INTERNACIONA 8083.80 23221.26
4       TOTAL OPERACION NACIONAL  970.00 20725.00
5  TOTAL OPERACION INTERNACIONAL  516.00  7289.00

In [28]:
# Estadísticas descriptivas para columnas numéricas
Data_Frame3.describe()

,ANIO,MES,TOTAL CARGA NACIONAL,TOTAL CARGA INTERNACIONA,TOTAL OPERACION NACIONAL,TOTAL OPERACION INTERNACIONAL
count,84.00,84.00,84.00,84.00,84.00,84.00
mean,2022.00,6.50,2141.48,16994.78,8205.62,4797.36
std,2.01,3.47,456.49,3034.68,2872.17,2002.71
min,2019.00,1.00,518.90,8083.80,970.00,516.00
25%,2020.00,3.75,1856.46,15013.04,7239.50,3405.25
50%,2022.00,6.50,2242.22,16798.31,9062.00,5439.00
75%,2024.00,9.25,2420.35,18466.62,9831.75,6537.75
max,2025.00,12.00,3141.59,23221.26,20725.00,7289.00

In [29]:
# Detección de outliers utilizando el método del IQR
numericos3 = Data_Frame3.select_dtypes(include='number')

q1_3 = numericos3.quantile(0.25)
q3_3 = numericos3.quantile(0.75)
iqr_3 = q3_3 - q1_3
outliers_3 = ((numericos3 < (q1_3 - 1.5 * iqr_3)) | (numericos3 > (q3_3 + 1.5 * iqr_3))).sum()

print("Número de outliers por columna:")
outliers_3

Número de outliers por columna:

ANIO                             0
MES                              0
TOTAL CARGA NACIONAL             2
TOTAL CARGA INTERNACIONA         1
TOTAL OPERACION NACIONAL         8
TOTAL OPERACION INTERNACIONAL    0
dtype: int64

In [30]:
# Función para ver los outliers por fila
mascara = (numericos3 < (q1_3 - 1.5 * iqr_3)) | (numericos3 > (q3_3 + 1.5 * iqr_3))
filas_outliers = Data_Frame3[mascara.any(axis=1)]
print(filas_outliers)

    ANIO  MES                  ENTIDAD PRESTADORA  \
5   2019    6  LIMA AIRPORT PARTNERS S.R.L. - LAP
15  2020    4  LIMA AIRPORT PARTNERS S.R.L. - LAP
16  2020    5  LIMA AIRPORT PARTNERS S.R.L. - LAP
17  2020    6  LIMA AIRPORT PARTNERS S.R.L. - LAP
18  2020    7  LIMA AIRPORT PARTNERS S.R.L. - LAP
19  2020    8  LIMA AIRPORT PARTNERS S.R.L. - LAP
20  2020    9  LIMA AIRPORT PARTNERS S.R.L. - LAP
25  2021    2  LIMA AIRPORT PARTNERS S.R.L. - LAP

                                CONCESION  TOTAL CARGA NACIONAL  \
5   AEROPUERTO INTERNACIONAL JORGE CHÁVEZ               2180.64
15  AEROPUERTO INTERNACIONAL JORGE CHÁVEZ                518.90
16  AEROPUERTO INTERNACIONAL JORGE CHÁVEZ               1083.96
17  AEROPUERTO INTERNACIONAL JORGE CHÁVEZ                926.91
18  AEROPUERTO INTERNACIONAL JORGE CHÁVEZ               1345.86
19  AEROPUERTO INTERNACIONAL JORGE CHÁVEZ               1317.20
20  AEROPUERTO INTERNACIONAL JORGE CHÁVEZ               1353.24
25  AEROPUERTO INTERNACIONAL JORGE CHÁVEZ               1433.03

    TOTAL CARGA INTERNACIONA  TOTAL OPERACION NACIONAL  \
5                   18544.43                     20725
15                   8083.80                       970
16                  11505.49                      1291
17                  11955.09                      1183
18                  12768.91                      1812
19                  13549.69                      1983
20                  14281.31                      2056
25                  12836.28                      3047

    TOTAL OPERACION INTERNACIONAL
5                            6614
15                            516
16                            614
17                            663
18                            665
19                            646
20                            759
25                           1905

# Análisis de outliers:
Se aplicó el método del Rango Intercuartílico (IQR) para detectar valores atípicos en las columnas numéricas. Si bien se identificaron valores fuera del rango intercuartílico en las columnas TOTAL CARGA NACIONAL, TOTAL CARGA INTERNACIONAL y TOTAL OPERACION NACIONAL, tras una revisión manual se determinó que corresponden a variaciones estacionales propias de la operación aeroportuaria, como el mes de junio 2019, siendo datos válidos y coherentes. Por ello se decidió conservar todos los registros sin eliminación ni imputación.

In [31]:
# Categorías raras
for col in Data_Frame3.select_dtypes(include='object').columns:
    print(f"\n{'='*40}")
    print(f"COLUMNA: {col}")
    print(f"Valores únicos: {Data_Frame3[col].nunique()}")
    vc = Data_Frame3[col].value_counts()
    raras = vc[vc < (len(Data_Frame3) * 0.01)]  # menos del 1%
    print(f"Categorías raras (< 1%): {len(raras)}")
    if len(raras) > 0:
        print(raras)
    else:
        print("Sin categorías raras ✅")

========================================
COLUMNA: ENTIDAD PRESTADORA
Valores únicos: 1
Categorías raras (< 1%): 0
Sin categorías raras ✅

========================================
COLUMNA: CONCESION
Valores únicos: 1
Categorías raras (< 1%): 0
Sin categorías raras ✅

In [32]:
# Tabla de métricas del tercer Dataset

# -- Completitud: Porcentaje de valores no nulos
completitud3 = round((1 - Data_Frame3.isnull().sum().sum() / Data_Frame3.size) * 100, 2)

# -- Unicidad: Porcentaje de filas únicas
unicidad3 = round((1 - Data_Frame3.duplicated().sum() / len(Data_Frame3)) * 100, 2)

# -- Consistencia: Porcentaje de columnas sin problemas de rango o formato
cols_totales3 = 8
cols_con_problema3 = 0
consistencia3 = round(((cols_totales3 - cols_con_problema3) / cols_totales3) * 100, 2)

# Creación de la tabla de métricas
tabla_metricas3 = pd.DataFrame({
    'Dataset': ["Información Trafico - Carga y Operaciones - LAP Ene 2019 - Dic 2025"],
    'Filas': [len(Data_Frame3)],
    'Completitud': [completitud3],
    'Unicidad': [unicidad3],
    'Consistencia': [consistencia3]
})

print("Métricas de calidad del dataset:")
tabla_metricas3

Métricas de calidad del dataset:

,Dataset,Filas,Completitud,Unicidad,Consistencia
0,Información Trafico - Carga y Operaciones - LA...,84,100.00,100.00,100.00

# PERFILADO DEL CUARTO DATASET

In [33]:
# Importación del cuarto dataset
Data_Frame4 = pd.read_csv(r'/content/drive/MyDrive/UAIN1008R_Proyecto/datos/raw/Transporte Terrestre Carga Internacional_2023-2024.csv')
print("Tamaño de la tabla: ", Data_Frame4.shape)

Data_Frame4.head()

Tamaño de la tabla:  (23950, 26)

,ID,RUC,RAZON_SOCIAL,FECHA_RESOLUCION,VIGENCIA_HASTA,MOTIVO_HABILITAC,TENENCIA,PERMISO_BLOQUE,PLACA,TIPO_SERVICIO,...,COMBUSTIBLE,CARGA_UTIL,P_SECO,P_BRUTO,LARGO,ANCHO,ALTO,N_ASIENTOS,N_LLANTAS,FECHA DE CORTE
0,1,20505370130,TERRACARGO SOCIEDAD ANONIMA CERRADA,20201021,20251021,Permiso de Oper. de Carga Internacional Regular,Propio,AMBOS,A0B975,REGULAR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20231231
1,2,20505370130,TERRACARGO SOCIEDAD ANONIMA CERRADA,20201021,20251021,Permiso de Oper. de Carga Internacional Regular,Propio,AMBOS,A0B977,REGULAR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20231231
2,3,20505370130,TERRACARGO SOCIEDAD ANONIMA CERRADA,20201021,20251021,Permiso de Oper. de Carga Internacional Regular,Propio,AMBOS,A0B982,REGULAR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20231231
3,4,20505370130,TERRACARGO SOCIEDAD ANONIMA CERRADA,20201130,20251021,Incremento,Propio,AMBOS,A0B993,REGULAR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20231231
4,5,20601844088,TRANSPORTES AMARTE ES MI DESTINO E.I.R.L.,20211109,20311109,Permiso de Oper. de Carga Internacional Regular,Propio,SUR,A0D887,REGULAR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20231231

In [34]:
# Tipos de datos
Data_Frame4.dtypes

ID                    int64
RUC                   int64
RAZON_SOCIAL         object
FECHA_RESOLUCION      int64
VIGENCIA_HASTA        int64
MOTIVO_HABILITAC     object
TENENCIA             object
PERMISO_BLOQUE       object
PLACA                object
TIPO_SERVICIO        object
CLASE                object
N_EJES                int64
ANIO_FAB            float64
N_CHASIS             object
N_MOTOR              object
MARCA                object
COMBUSTIBLE          object
CARGA_UTIL          float64
P_SECO              float64
P_BRUTO             float64
LARGO               float64
ANCHO               float64
ALTO                float64
N_ASIENTOS          float64
N_LLANTAS           float64
FECHA DE CORTE        int64
dtype: object

In [35]:
# Total de nulos y % de nulos por columna
nulos4 = Data_Frame4.isnull().sum()
porcentaje_nulos4 = (Data_Frame4.isnull().mean() * 100).round(2)

tabla_nulos4 = pd.DataFrame({'Total Nulos': nulos4, 'Porcentaje Nulos': porcentaje_nulos4})

print("REPORTE DE VALORES NULOS: ")
tabla_nulos4

REPORTE DE VALORES NULOS:

                  Total Nulos  Porcentaje Nulos
ID                          0              0.00
RUC                         0              0.00
RAZON_SOCIAL                0              0.00
FECHA_RESOLUCION            0              0.00
VIGENCIA_HASTA              0              0.00
MOTIVO_HABILITAC            0              0.00
TENENCIA                    0              0.00
PERMISO_BLOQUE              0              0.00
PLACA                       0              0.00
TIPO_SERVICIO               0              0.00
CLASE                       0              0.00
N_EJES                      0              0.00
ANIO_FAB                12238             51.10
N_CHASIS                12238             51.10
N_MOTOR                 12256             51.17
MARCA                   12238             51.10
COMBUSTIBLE             12238             51.10
CARGA_UTIL              12238             51.10
P_SECO                  12238             51.10
P_BRUTO                 12238             51.10
LARGO                   12238             51.10
ANCHO                   12238             51.10
ALTO                    12238             51.10
N_ASIENTOS              12251             51.15
N_LLANTAS               12251             51.15
FECHA DE CORTE              0              0.00

In [36]:
# Número de filas duplicadas
duplicados4 = Data_Frame4.duplicated().sum()

print("Número de filas duplicadas: ", duplicados4)

Número de filas duplicadas:  0

In [37]:
# Rangos inconsistentes
tabla_rangos4 = pd.DataFrame({
    'CATEGORIA': ['ID', 'RUC','FECHA_RESOLUCION','VIGENCIA_HASTA','N_EJES','ANIO_FAB','CARGA_UTIL','P_SECO','P_BRUTO','LARGO','ANCHO','ALTO','N_ASIENTOS','N_LLANTAS','FECHA DE CORTE'],
    'MINIMO': [Data_Frame4['ID'].min(), Data_Frame4['RUC'].min(), Data_Frame4['FECHA_RESOLUCION'].min(), Data_Frame4['VIGENCIA_HASTA'].min(), Data_Frame4['N_EJES'].min(), Data_Frame4['ANIO_FAB'].min(), Data_Frame4['CARGA_UTIL'].min(), Data_Frame4['P_SECO'].min(), Data_Frame4['P_BRUTO'].min(), Data_Frame4['LARGO'].min(), Data_Frame4['ANCHO'].min(), Data_Frame4['ALTO'].min(), Data_Frame4['N_ASIENTOS'].min(), Data_Frame4['N_LLANTAS'].min(), Data_Frame4['FECHA DE CORTE'].min()],
    'MAXIMO': [Data_Frame4['ID'].max(), Data_Frame4['RUC'].max(), Data_Frame4['FECHA_RESOLUCION'].max(), Data_Frame4['VIGENCIA_HASTA'].max(), Data_Frame4['N_EJES'].max(), Data_Frame4['ANIO_FAB'].max(), Data_Frame4['CARGA_UTIL'].max(), Data_Frame4['P_SECO'].max(), Data_Frame4['P_BRUTO'].max(), Data_Frame4['LARGO'].max(), Data_Frame4['ANCHO'].max(), Data_Frame4['ALTO'].max(), Data_Frame4['N_ASIENTOS'].max(), Data_Frame4['N_LLANTAS'].max(), Data_Frame4['FECHA DE CORTE'].max()]
})

tabla_rangos4

           CATEGORIA         MINIMO         MAXIMO
0                 ID           1.00       23950.00
1                RUC 20100192901.00 20613305409.00
2   FECHA_RESOLUCION    19960410.00    20241227.00
3     VIGENCIA_HASTA        6148.00    20410801.00
4             N_EJES           1.00           9.00
5           ANIO_FAB        1958.00        2025.00
6         CARGA_UTIL           0.00       39611.00
7             P_SECO           1.10       20930.00
8            P_BRUTO           0.00      384300.00
9              LARGO           1.50          19.20
10             ANCHO           0.00           4.00
11              ALTO           0.00           4.30
12        N_ASIENTOS           0.00           6.00
13         N_LLANTAS           0.00          48.00
14    FECHA DE CORTE    20231231.00    20241231.00

In [38]:
# Estadísticas descriptivas para columnas numéricas
Data_Frame4.describe()

,ID,RUC,FECHA_RESOLUCION,VIGENCIA_HASTA,N_EJES,ANIO_FAB,CARGA_UTIL,P_SECO,P_BRUTO,LARGO,ANCHO,ALTO,N_ASIENTOS,N_LLANTAS,FECHA DE CORTE
count,23950.00,23950.00,23950.00,23950.00,23950.00,11712.00,11712.00,11712.00,11712.00,11712.00,11712.00,11712.00,11699.00,11699.00,23950.00
mean,11975.50,20439879471.98,20198587.45,20276751.33,2.90,2011.98,66.13,23.92,118.86,10.26,2.54,3.44,1.04,9.92,20236121.19
std,6913.91,171281058.15,32129.71,508359.81,0.37,8.50,1073.41,416.99,3812.74,2.98,0.11,0.58,1.07,2.31,4998.90
min,1.00,20100192901.00,19960410.00,6148.00,1.00,1958.00,0.00,1.10,0.00,1.50,0.00,0.00,0.00,0.00,20231231.00
25%,5988.25,20371332210.00,20180202.00,20261025.00,3.00,2008.00,17.30,7.20,25.00,7.60,2.50,3.20,0.00,8.00,20231231.00
50%,11975.50,20506040044.00,20210621.00,20290227.00,3.00,2013.00,23.85,7.90,31.00,9.50,2.60,3.50,1.00,10.00,20231231.00
75%,17962.75,20554357238.00,20220902.00,20311216.00,3.00,2017.00,30.82,8.70,39.00,13.00,2.60,3.90,2.00,12.00,20241231.00
max,23950.00,20613305409.00,20241227.00,20410801.00,9.00,2025.00,39611.00,20930.00,384300.00,19.20,4.00,4.30,6.00,48.00,20241231.00

In [39]:
# Detección de outliers utilizando el método del IQR
numericos4 = Data_Frame4.select_dtypes(include='number')

q1_4 = numericos4.quantile(0.25)
q3_4 = numericos4.quantile(0.75)
iqr_4 = q3_4 - q1_4
outliers_4 = ((numericos4 < (q1_4 - 1.5 * iqr_4)) | (numericos4 > (q3_4 + 1.5 * iqr_4))).sum()

print("Número de outliers por columna:")
outliers_4

Número de outliers por columna:

ID                     0
RUC                    0
FECHA_RESOLUCION     226
VIGENCIA_HASTA        28
N_EJES              3278
ANIO_FAB             547
CARGA_UTIL            37
P_SECO               714
P_BRUTO               91
LARGO                  0
ANCHO                334
ALTO                 496
N_ASIENTOS             2
N_LLANTAS             20
FECHA DE CORTE         0
dtype: int64

In [40]:
# Función para ver los outliers por fila
mascara = (numericos4 < (q1_4 - 1.5 * iqr_4)) | (numericos4 > (q3_4 + 1.5 * iqr_4))
filas_outliers = Data_Frame4[mascara.any(axis=1)]
print(filas_outliers)

          ID          RUC                           RAZON_SOCIAL  \
7          8  20550946671       SOLUCION AMBIENTAL MAYEMA S.A.C.
11        12  20532703876                GRUPO ALTAMIRA S. A. C.
16        17  20494966990          INVERSIONES YOYITO'S E.I.R.L.
22        23  20495593305      TRANSPORTES UNIDOS DEL SUR S.A.C.
23        24  20495593305      TRANSPORTES UNIDOS DEL SUR S.A.C.
...      ...          ...                                    ...
23937  23938  20521180774                          ZGROUP S.A.C.
23938  23939  20521180774                          ZGROUP S.A.C.
23939  23940  20521180774                          ZGROUP S.A.C.
23944  23945  20602749801  24/7 LOGISTICA Y TRANSPORTES E.I.R.L.
23949  23950  20532519609                3V INVERSIONES E.I.R.L.

       FECHA_RESOLUCION  VIGENCIA_HASTA  \
7              20160122        20260122
11             20220412        20320412
16             20160229        20260228
22             20110407        20320624
23             20110407        20320624
...                 ...             ...
23937          20160902        20251020
23938          20160902        20251020
23939          20151020        20251020
23944          20220331        20320331
23949          20240205        20340205

                                      MOTIVO_HABILITAC TENENCIA  \
7      Permiso de Oper. de Carga Internacional Regular   Propio
11     Permiso de Oper. de Carga Internacional Regular   Propio
16     Permiso de Oper. de Carga Internacional Regular   Propio
22                                          Incremento   Propio
23                                          Incremento   Propio
...                                                ...      ...
23937                                       Incremento   Propio
23938                                       Incremento   Propio
23939  Permiso de Oper. de Carga Internacional Regular   Propio
23944  Permiso de Oper. de Carga Internacional Regular   Propio
23949  Permiso de Oper. de Carga Internacional Regular   Propio

      PERMISO_BLOQUE   PLACA TIPO_SERVICIO  ...      COMBUSTIBLE  CARGA_UTIL  \
7                SUR  A0E854       REGULAR  ...              NaN         NaN
11               SUR  A0H902       REGULAR  ...              NaN         NaN
16               SUR  A0M913       REGULAR  ...              NaN         NaN
22               SUR  A0O989       REGULAR  ...              NaN         NaN
23               SUR  A0O990       REGULAR  ...              NaN         NaN
...              ...     ...           ...  ...              ...         ...
23937            SUR  C3R988       REGULAR  ...  SIN COMBUSTIBLE    31700.00
23938            SUR  C4T994       REGULAR  ...              S/C       30.70
23939            SUR  D1K852       REGULAR  ...           DIESEL       18.00
23944            SUR  A7X978       REGULAR  ...              S/C       30.00
23949            SUR  BUB780       REGULAR  ...           DIESEL        1.60

       P_SECO  P_BRUTO LARGO ANCHO ALTO  N_ASIENTOS  N_LLANTAS  FECHA DE CORTE
7         NaN      NaN   NaN   NaN  NaN         NaN        NaN        20231231
11        NaN      NaN   NaN   NaN  NaN         NaN        NaN        20231231
16        NaN      NaN   NaN   NaN  NaN         NaN        NaN        20231231
22        NaN      NaN   NaN   NaN  NaN         NaN        NaN        20231231
23        NaN      NaN   NaN   NaN  NaN         NaN        NaN        20231231
...       ...      ...   ...   ...  ...         ...        ...             ...
23937 3300.00 35000.00 12.20  0.00 1.60         NaN        NaN        20241231
23938    3.10    33.80 14.60  2.30 1.20        0.00       8.00        20241231
23939    7.00    25.00  6.40  2.50 3.80        3.00      10.00        20241231
23944    8.20    38.20 13.20  2.60 3.50        0.00      12.00        20241231
23949    1.90     3.50  5.20  1.90 2.60        3.00       6.00        20241231

[4482 rows x 26 columns]

# Análisis de outliers:
Se aplicó el método del Rango Intercuartílico (IQR) para detectar valores atípicos en las columnas numéricas. Los valores fuera del rango intercuartílico detectados responden a dos factores: la variedad natural del parque vehicular registrado, donde el número de ejes (N_EJES) varía legítimamente entre 2 y 4 según el tipo de vehículo, y el alto porcentaje de nulos en columnas técnicas como ANIO_FAB, CARGA_UTIL y P_BRUTO, que distorsionan el cálculo del IQR al no contar con suficientes datos. Tras la revisión manual se determinó que ningún valor constituye un error real, por lo que se decidió conservar todos los registros sin eliminación ni imputación.

In [41]:
# Categorías raras
for col in Data_Frame4.select_dtypes(include='object').columns:
    print(f"\n{'='*40}")
    print(f"COLUMNA: {col}")
    print(f"Valores únicos: {Data_Frame4[col].nunique()}")
    vc = Data_Frame4[col].value_counts()
    raras = vc[vc < (len(Data_Frame4) * 0.01)]  # menos del 1%
    print(f"Categorías raras (< 1%): {len(raras)}")
    if len(raras) > 0:
        print(raras)
    else:
        print("Sin categorías raras ✅")

========================================
COLUMNA: RAZON_SOCIAL
Valores únicos: 1307
Categorías raras (< 1%): 1296
RAZON_SOCIAL
STIERLIFT S.A.                                          228
TRANSPORTES KALÁ SOCIEDAD ANONIMA CERRADA               218
CORPORACION ADC S.A.C.                                  204
TRANSPORTES MERIDIAN S.A.C.                             200
GRUPO CAVASSA S.A.C.                                    199
                                                       ...
TRANSPORTE SERNA ALTAMIRANO S.R.L. - TRASERAL S.R.L.      1
FERMAT MANTENIMIENTO Y CONSTRUCCION E.I.R.L.              1
TRANSPORTE INTERNACIONAL SUPARO S.A.C.                    1
VIATORI SOCIEDAD ANONIMA CERRADA - VIATORI S.A.C.         1
3V INVERSIONES E.I.R.L.                                   1
Name: count, Length: 1296, dtype: int64

========================================
COLUMNA: MOTIVO_HABILITAC
Valores únicos: 3
Categorías raras (< 1%): 1
MOTIVO_HABILITAC
Permiso de Oper. de Carga Internacional por Cuenta Propia    14
Name: count, dtype: int64

========================================
COLUMNA: TENENCIA
Valores únicos: 4
Categorías raras (< 1%): 1
TENENCIA
SIN TENENCIA    13
Name: count, dtype: int64

========================================
COLUMNA: PERMISO_BLOQUE
Valores únicos: 3
Categorías raras (< 1%): 0
Sin categorías raras ✅

========================================
COLUMNA: PLACA
Valores únicos: 13358
Categorías raras (< 1%): 13358
PLACA
Z8E711    2
Z8D918    2
Z7Z932    2
Z7Z817    2
Z7Y914    2
         ..
VAU976    1
C0K997    1
CBO707    1
CBN948    1
BZG821    1
Name: count, Length: 13358, dtype: int64

========================================
COLUMNA: TIPO_SERVICIO
Valores únicos: 2
Categorías raras (< 1%): 1
TIPO_SERVICIO
CUENTA PROPIA    26
Name: count, dtype: int64

========================================
COLUMNA: CLASE
Valores únicos: 6
Categorías raras (< 1%): 2
CLASE
CMTA PICKUP    56
CMTA PANEL      7
Name: count, dtype: int64

========================================
COLUMNA: N_CHASIS
Valores únicos: 11686
Categorías raras (< 1%): 11686
N_CHASIS
-                    26
4V4NC9TJ93N348106     2
8T9ES34BR8PDC1070     1
8T9340NFR7DC18001     1
8T9340NFR7DC18003     1
                     ..
1FUJA6CG26LV86536     1
8S9SC23C4DAS87016     1
3AKJF0CV5HDHV8117     1
8T9S340P08NDL2211     1
8T9KVRSP1FTA18159     1
Name: count, Length: 11686, dtype: int64

========================================
COLUMNA: N_MOTOR
Valores únicos: 5891
Categorías raras (< 1%): 5889
N_MOTOR
S             91
NOTIENE       22
NE            11
00000         10
00             8
              ..
MP81182250     1
MP81184457     1
MP81160205     1
MP81063361     1
79248799       1
Name: count, Length: 5889, dtype: int64

========================================
COLUMNA: MARCA
Valores únicos: 427
Categorías raras (< 1%): 417
MARCA
MACK               226
FACTORIA J.F.C.    202
SGM INGENIEROS     180
LIM                175
RMB SATECI         173
                  ...
COMET                1
TRAIL                1
FRUEHAUF.            1
STOUGHTON            1
JD-BERTOLINI         1
Name: count, Length: 417, dtype: int64

========================================
COLUMNA: COMBUSTIBLE
Valores únicos: 14
Categorías raras (< 1%): 10
COMBUSTIBLE
GNV                     32
SIN COMBUSTIBLE         30
SIN DEFINIR             25
GNL                      9
NO MUESTRA               7
SIN VALOR                5
BI-COMBUSTIBLE GLP       3
GASOLINA                 3
BI - COMBUSTIBLE GLP     1
DUAL GLP                 1
Name: count, dtype: int64

In [42]:
# Tabla de métricas del cuarto Dataset

# -- Completitud: Porcentaje de valores no nulos
completitud4 = round((1 - Data_Frame4.isnull().sum().sum() / Data_Frame4.size) * 100, 2)

# -- Unicidad: Porcentaje de filas únicas
unicidad4 = round((1 - Data_Frame4.duplicated().sum() / len(Data_Frame4)) * 100, 2)

# -- Consistencia: Porcentaje de columnas sin problemas de rango o formato
cols_totales4 = 26
cols_con_problema4 = 13
consistencia4 = round(((cols_totales4 - cols_con_problema4) / cols_totales4) * 100, 2)

# Creación de la tabla de métricas
tabla_metricas4 = pd.DataFrame({
    'Dataset': ["Transporte Terrestre Carga Internacional_2023-2024"],
    'Filas': [len(Data_Frame4)],
    'Completitud': [completitud4],
    'Unicidad': [unicidad4],
    'Consistencia': [consistencia4]
})

print("Métricas de calidad del dataset:")
tabla_metricas4

Métricas de calidad del dataset:

,Dataset,Filas,Completitud,Unicidad,Consistencia
0,Transporte Terrestre Carga Internacional_2023-...,23950,74.44,100.00,50.00

# Clasificación de cada Dataset:
- Primer Dataset _"Red vial nacional del Sistema Nacional de Carreteras 2022 a 2024"_: Completitud 100% · Unicidad 100% · Consistencia 85.71% → ALTA ✅ - Dataset completo sin nulos ni duplicados. La consistencia es ligeramente menor debido a valores negativos en NRO_CARRILES y ESTADO, y una categoría duplicada en SUPERFICIE_L, problemas menores que serán corregidos en el ETL.

- Segundo Dataset _"Dataset GEI CSV_0"_: Completitud 74.36% · Unicidad 100% · Consistencia 85.71%
→ MEDIA ALTA ⚠️ - Dataset con relativo porcentaje de nulos en todas las columnas, sin duplicadosy un bajo porcentaje de inconsistencias que afectan la completitud. La consistencia baja se debe a inconsistencias en la columna DIOXIDO_DE_CARBONO_GGCO2 con categorías negativas y valores sin estandarizar, y en las columnas METANO_GGCH4,	METANO_EQUIVALENTE_GGCO2EQ,	OXIDO_NITROSO_GGN2O,	OXIDO_NITROSO_EQUIVALENTE_GGCO2EQ,	HFC_GGCO2EQ con valores nulos y falta de normalización en las columnas FECHA_CORTE y	ANIO. Será tratado en el ETL.

- Tercer Dataset _"Información Trafico - Carga y Operaciones - LAP Ene 2019 - Dic 2025"_: Completitud 100% · Unicidad 100% · Consistencia 100%
→ ALTA ✅ - Dataset íntegro sin nulos, duplicados ni inconsistencias. Los valores atípicos detectados corresponden a variaciones operativas estacionales válidas.

- Cuarto Dataset _"Transporte Terrestre Carga Internacional 2023 2024"_: Completitud 74.44% · Unicidad 100% · Consistencia 50% → MEDIA ⚠️ - Dataset con alto porcentaje de nulos en columnas técnicas del vehículo (ANIO_FAB, MARCA, COMBUSTIBLE, entre otras) que afectan la completitud. La consistencia baja se debe a inconsistencias en la columna COMBUSTIBLE con categorías duplicadas y valores sin estandarizar, y en la columna N_MOTOR con valores ambiguos ("S", "NE") y múltiples formas de representar ausencia de dato ("NOTIENE", "00000", "00"). Será tratado en el ETL.

ETL: _Extract, Transform, Load_

# 🚩 Lista Priorizada de Problemas de Datos
**🔴 Nivel Crítico **(Requiere intervención inmediata en ETL)


**Dataset 2** - Vacíos en Gases GEI: Las columnas OXIDO_NITROSO_GGN2O (49.16% nulos) y METANO_GGCH4 (45.25% nulos) comprometen el análisis total de emisiones. La columna HFC_GGCO2EQ (98.04% nulos) es prácticamente inservible.


Acción: Evaluar si los nulos significan "cero emisiones" o falta de medición. Eliminar la columna HFC.


Dataset 4 - Información Técnica Ausente: Más del 51% de nulos en ANIO_FAB, MARCA, COMBUSTIBLE y pesos (P_BRUTO, P_SECO).

Acción: Decidir si se conservan los registros basándose solo en la razón social o si se eliminan por falta de datos técnicos.

Dataset 4 - Caos en 'COMBUSTIBLE': Multiplicidad de etiquetas para nulos ("SIN DEFINIR", "NO MUESTRA", "SIN VALOR") y errores de digitación ("BI-COMBUSTIBLE" vs "BI - COMBUSTIBLE").

Acción: Estandarizar usando .replace() y .str.strip().

🟡 Nivel Medio (Problemas de consistencia y formato)
Dataset 1 - Valores Imposibles: Presencia de -1.00 en las columnas NRO_CARRILES y ESTADO.

Acción: Filtrar o imputar por la moda de la vía/región, ya que un carril negativo es físicamente imposible.

Dataset 4 - Identificadores de Motor: La columna N_MOTOR contiene valores basura como "S", "NE", "00000" o "NOTIENE".

Acción: Unificar a una categoría "NO REGISTRADO".

Dataset 2 - Nulos en Jerarquía: SUBCATEGORIA (8.10% nulos) y FUENTE_DE_EMISION (15.92% nulos) faltantes.

Acción: Imputar basándose en la clasificación IPCC_CLASF que sí está presente al 99.7%.

🟢 Nivel Bajo (Refinamiento estético)
Dataset 1 - Errores de Género en Texto: Categorías "Proyectado" y "Proyectada" en SUPERFICIE_L.

Acción: Unificar a "Proyectado".

Dataset 3 - Outliers Estacionales: Valores altos en carga nacional/internacional en junio 2019.

Acción: Ninguna (solo documentar), ya que representan picos reales de operación.